services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DB_PATH=/app/vpn.db
      - LOOP_MODE=true
    restart: unless-stopped

