services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    