services:
  backend:
    image: ghcr.io/ras1putra/vpn-gate-backend:latest
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: unless-stopped

  scraper:
    image: ghcr.io/ras1putra/vpn-gate-scraper:latest
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=/data/vpn.db
      - LOOP_MODE=true
    restart: unless-stopped


